Controllers/AdminController.cs
using Emlak.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Emlak.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        DataContext db = new DataContext();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IlanListesi()
        {
            var ilan = db.Ilans.Include(i => i.Mahalle).Include(i => i.Tip).ToList();
            return View(ilan);
        }
    }
}

Controllers/SehirController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Emlak.Models;

namespace Emlak.Controllers
{
    public class SehirController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Sehir
        public ActionResult Index()
        {
            return View(db.Sehirs.ToList());
        }

        // GET: Sehir/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sehir sehir = db.Sehirs.Find(id);
            if (sehir == null)
            {
                return HttpNotFound();
            }
            return View(sehir);
        }

        // GET: Sehir/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sehir/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SehirId,SehirAd")] Sehir sehir)
        {
            if (ModelState.IsValid)
            {
                db.Sehirs.Add(sehir);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sehir);
        }

        // GET: Sehir/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sehir sehir = db.Sehirs.Find(id);
            if (sehir == null)
            {
                return HttpNotFound();
            }
            return View(sehir);
        }

        // POST: Sehir/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SehirId,SehirAd")] Sehir sehir)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sehir).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sehir);
        }

        // GET: Sehir/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sehir sehir = db.Sehirs.Find(id);
            if (sehir == null)
            {
                return HttpNotFound();
            }
            return View(sehir);
        }

        // POST: Sehir/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sehir sehir = db.Sehirs.Find(id);
            db.Sehirs.Remove(sehir);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Admin/IlanListesi.cshtml
@model IEnumerable<Emlak.Models.Ilan>
@{
    ViewBag.Title = "IlanListesi";
}


<div class="container">

    <div class="row">
        <div class="col-md-3">
            <br />
            <!--Filtreleme Kısmı-->
            <form class="form-horizontal">
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">En Az</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="En Az(Fiyat)">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">En Çok</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="En Çok(Fiyat)">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Şehir</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Şehir">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Semt</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Semt">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Mahalle</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Mahalle">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Durum</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Durum">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Tip</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Tip">
                    </div>
                </div>



                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label"></label>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-search" aria-hidden="true"></i> FİLTRELEME</button>
                    </div>
                </div>
            </form>
        </div>

        <!--ilan Listesi-->
        <br />
        <div class="col-md-9">
            <div class="thumbnail" style="width:845px;">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/Admin/Index">Admin Sayfası</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Ilan Listesi</li>
                    </ol>
                </nav>

                <br />
                <table class="table">
                    <tr>
                        <th>
                            Kullanıcı Adı
                        </th>
                        <th>
                            Mahalle
                        </th>
                        <th>
                            Tip
                        </th>


                        <th>
                            Adres
                        </th>

                        <th>
                            Şehir
                        </th>
                        <th>
                            Semt
                        </th>
                        <th>
                            Durum
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                              <button class="btn btn-primary">@item.UserName</button>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.MahalleAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tip.TipAd)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Adres)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.Semt.Sehir.SehirAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.Semt.SemtAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tip.Durum.DurumAd)
                            </td>
                            <td>
                               
                                <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.IlanId })"><i class="fa fa-trash" aria-hidden="true"></i> Sil</a>
                            </td>
                        </tr>
                    }

                </table>

            </div>
        </div>
    </div>
</div>

Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="container">

    <div class="row">
        <div class="col-md-3">
            <br />
            <!--Filtreleme Kısmı-->
            <form class="form-horizontal">
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">En Az</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="En Az(Fiyat)">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">En Çok</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="En Çok(Fiyat)">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Şehir</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Şehir">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Semt</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Semt">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Mahalle</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Mahalle">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Durum</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Durum">
                    </div>
                </div>
                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label">Tip</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Tip">
                    </div>
                </div>



                <div class="form-group ">
                    <label for="inputEmail3" class="col-sm-4 control-label"></label>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-search" aria-hidden="true"></i> FİLTRELEME</button>
                    </div>
                </div>
            </form>
        </div>

        <!--ilan Listesi-->
        <br />
        <div class="col-md-9">
            <div class="thumbnail" style="width:845px; height:400px">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/Admin/Index">Admin Sayfası</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Anasayfa</li>
                    </ol>
                </nav>
               <div class="col-md-3">
                   <div class="thumbnail">
                       <img src="~/Content/images/analiz.jpg" style="height:50px"/>
                       <div class="caption">
                           <p>@Html.ActionLink("Şehir Listesi","Index","Sehir",null,new { @class="btn btn-success btn-block"})</p>
                       </div>
                   </div>
               </div>
                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="~/Content/images/analiz.jpg" style="height:50px" />
                        <div class="caption">
                            <p>@Html.ActionLink("Semt Listesi", "Index", "Semt", null, new { @class = "btn btn-info btn-block" })</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="~/Content/images/analiz.jpg" style="height:50px" />
                        <div class="caption">
                            <p>@Html.ActionLink("Mahalle Listesi", "Index", "Mahalle", null, new { @class = "btn btn-primary btn-block" })</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="~/Content/images/analiz.jpg" style="height:50px" />
                        <div class="caption">
                            <p>@Html.ActionLink("Durum Listesi", "Index", "Durum", null, new { @class = "btn btn-warning btn-block" })</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="~/Content/images/analiz.jpg" style="height:50px" />
                        <div class="caption">
                            <p>@Html.ActionLink("Tip Listesi", "Index", "Tip", null, new { @class = "btn btn-success btn-block" })</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="~/Content/images/analiz.jpg" style="height:50px" />
                        <div class="caption">
                            <p>@Html.ActionLink("Ilan Listesi", "IlanListesi", "Admin", null, new { @class = "btn btn-info btn-block" })</p>
                        </div>
                    </div>
                </div>



            </div>
        </div>
    </div>
</div>