Controllers/TipController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Emlak.Models;

namespace Emlak.Controllers
{
    public class TipController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Tip
        public ActionResult Index()
        {
            var tips = db.Tips.Include(t => t.Durum);
            return View(tips.ToList());
        }
        public PartialViewResult DurumAd1()
        {
            var durumad1 = db.Tips.Where(i => i.DurumId == 1).FirstOrDefault();
            return PartialView(durumad1);
        }
        public PartialViewResult DurumAd2()
        {
            var durumad2 = db.Tips.Where(i => i.DurumId == 2).FirstOrDefault();
            return PartialView(durumad2);
        }
        public PartialViewResult DurumTip1()
        {
            var durumtip1 = db.Tips.Where(i => i.DurumId == 1).ToList();
            return PartialView(durumtip1);
        }
        public PartialViewResult DurumTip2()
        {
            var durumtip2 = db.Tips.Where(i => i.DurumId == 2).ToList();
            return PartialView(durumtip2);
        }

        // GET: Tip/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            return View(tip);
        }

        // GET: Tip/Create
        public ActionResult Create()
        {
            ViewBag.DurumId = new SelectList(db.Durums, "DurumId", "DurumAd");
            return View();
        }

        // POST: Tip/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TipId,TipAd,DurumId")] Tip tip)
        {
            if (ModelState.IsValid)
            {
                db.Tips.Add(tip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DurumId = new SelectList(db.Durums, "DurumId", "DurumAd", tip.DurumId);
            return View(tip);
        }

        // GET: Tip/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            ViewBag.DurumId = new SelectList(db.Durums, "DurumId", "DurumAd", tip.DurumId);
            return View(tip);
        }

        // POST: Tip/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TipId,TipAd,DurumId")] Tip tip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DurumId = new SelectList(db.Durums, "DurumId", "DurumAd", tip.DurumId);
            return View(tip);
        }

        // GET: Tip/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            return View(tip);
        }

        // POST: Tip/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tip tip = db.Tips.Find(id);
            db.Tips.Remove(tip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/Arama.cshtml
@using (Html.BeginForm("Search", "Home", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
    {

    <div class="form-group">
        <input type="text" class="form-control" name="q" placeholder="Arama">
    </div>
    <button type="submit" class="btn btn-primary"> <i class="fa fa-search" aria-hidden="true"></i> Ara</button>

}

Views/Shared/LoginPartial.cshtml
<ul class="nav navbar-nav navbar-right">
    @if (Request.IsAuthenticated)
    {
        if (this.User.IsInRole("admin"))
        {
            <li><a href="/Admin/Index" style="color:white">Admin Paneli</a></li>
            <li><a href="/Ilan/Index" style="color:white">@User.Identity.Name</a></li>
            <li><a href="/Account/Profil" style="color:white">Profilim</a></li>
            <div class="nav navbar-nav navbar-right" style="padding:10px">
                
                <a href="/Account/LogOut" class="btn btn-danger"><i class="fa fa-remove" aria-hidden="true"></i> Çıkış</a>
                <a href="/Ilan/Create" class="btn btn-info"><i class="fa fa-bullhorn" aria-hidden="true"></i> İLAN VER</a>

            </div>
        }
        else
        {
            <li><a href="/Ilan/Index" style="color:white">@User.Identity.Name</a></li>
            <li><a href="/Account/Profil" style="color:white">Profilim</a></li>
            <div class="nav navbar-nav navbar-right" style="padding:10px">

                <a href="/Account/LogOut" class="btn btn-danger"><i class="fa fa-remove" aria-hidden="true"></i> Çıkış</a>
                <a href="/Ilan/Create" class="btn btn-info"><i class="fa fa-bullhorn" aria-hidden="true"></i> İLAN VER</a>

            </div>
        }
    }
    else
    {
        <div class="nav navbar-nav navbar-right" style="padding:10px">
            <a href="/Account/Register" class="btn btn-primary"><i class="fa fa-users" aria-hidden="true"></i> Üye Ol</a>
            <a href="/Account/Login" class="btn btn-success"><i class="fa fa-sign-in" aria-hidden="true"></i> Giriş</a>
            <a href="/Account/Login" class="btn btn-info"><i class="fa fa-bullhorn" aria-hidden="true"></i> İLAN VER</a>

        </div>
    }
   

</ul>

Views/Shared/MahallePartial.cshtml
<option value="">Mahalle Seç</option>
@if(ViewBag.mahallelistesi!=null)
{
    foreach (var item in ViewBag.mahallelistesi)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

Views/Shared/SemtPartial.cshtml
<option value="">Semt Seç</option>
@if (ViewBag.semtlistesi!=null)
{
    foreach (var item in ViewBag.semtlistesi)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

Views/Shared/TipPartial.cshtml
<option value="">Tip Seç</option>
@if (ViewBag.tiplistesi!=null)
{
    foreach (var item in ViewBag.tiplistesi)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Emlak Sitesi</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- Bootstrap -->
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/Content/js/bootstrap.min.js"></script>

</head>
<body>
    <header>
        <!--menü çubuğu-->
        <div class="container">
            <br />
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" style="padding:10px" href="/Home/Index"> <img src="/Content/images/logo.png" width="110" /></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                       @Html.Partial("Arama")
                        <ul class="nav navbar-nav navbar-left">

                            <li class="dropdown">
                                @Html.Action("DurumAd1", "Tip")
                                <ul class="dropdown-menu">
                                   @Html.Action("DurumTip1","Tip")

                                </ul>
                            </li>
                            <li class="dropdown">
                                @Html.Action("DurumAd2", "Tip")
                                <ul class="dropdown-menu">
                                    @Html.Action("DurumTip2", "Tip")

                                </ul>
                            </li>
                        </ul>
                      @Html.Partial("LoginPartial")
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </div>

    </header>
   @RenderBody()
    <footer>
        <!--footer-->
        <div class="container">
            <div class="row well" style="background-color:black">
                <div class="col-md-9">
                    <h5 class="text-uppercase" style="color:white">İLETİŞİM</h5>
                    <ul class="list-unstyled">
                        <li><a href="/Account/Login" style="color:white"> GİRİŞ</a></li>
                        <li><a href="/Account/Register" style="color:white"> ÜYE OL</a></li>
                       @Html.Action("Durum","Durum")
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5 class="text-uppercase" style="color:white">SOSYAL MEDYA</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="https://www.facebook.com/" style="color:white"> <img src="/Content/images/facebook.png" width="50" /></a>
                            <a href="https://twitter.com/explore" style="color:white"> <img src="/Content/images/twitter.png" width="50" /></a>
                            <a href="https://www.youtube.com/" style="color:white"> <img src="/Content/images/youtube.png" width="50" /></a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </footer>


</body>
</html>