Models/Ilan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Emlak.Models
{
    public class Ilan
    {
        public int IlanId { get; set; }
        public string Açıklama { get; set; }
        public double Fiyat { get; set; }
        public int OdaSayisi { get; set; }
        public int BanyoSayisi { get; set; }
        public bool Kredi { get; set; }
        public int Alan { get; set; }
        public string Kat { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string UserName { get; set; }
        public int SehirId { get; set; }
        public int SemtId { get; set; }
        public int DurumId { get; set; }

        public int MahalleId { get; set; }
        public Mahalle Mahalle { get; set; }

        public int TipId { get; set; }
        public Tip Tip { get; set; }
        public List<Resim> Resims { get; set; }
    }
}

Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Emlak.Models;
using System.IO;

namespace Emlak.Controllers
{
    public class IlanController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Ilan
        public ActionResult Index()
        {
            var username = User.Identity.Name;

            var ilans = db.Ilans.Where(i=>i.UserName==username).Include(i => i.Mahalle).Include(i => i.Tip);
            return View(ilans.ToList());
        }
        public List<Sehir> SehirGetir()
        {
            List<Sehir> sehirler = db.Sehirs.ToList();
            return sehirler;
        }
        public ActionResult SemtGetir(int SehirId)
        {
            List<Semt> semtlist = db.Semts.Where(x => x.SehirId == SehirId).ToList();
            ViewBag.semtlistesi = new SelectList(semtlist, "SemtId", "SemtAd");
            return PartialView("SemtPartial");
        }
        public ActionResult MahalleGetir(int SemtId)
        {
            List<Mahalle> mahallelist = db.Mahalles.Where(x => x.SemtId == SemtId).ToList();
            ViewBag.mahallelistesi = new SelectList(mahallelist, "MahalleId", "MahalleAd");
            return PartialView("MahallePartial");
        }
        public List<Durum> DurumGetir()
        {
            List<Durum> durumlar = db.Durums.ToList();
            return durumlar;
        }
        public ActionResult TipGetir(int DurumId)
        {
            List<Tip> tiplist = db.Tips.Where(x => x.DurumId == DurumId).ToList();
            ViewBag.tiplistesi = new SelectList(tiplist, "TipId", "TipAd");
            return PartialView("TipPartial");
        }
        public ActionResult Images(int id)
        {
            var ilan = db.Ilans.Where(i => i.IlanId == id).ToList();
            var rsml = db.Resims.Where(i => i.IlanId == id).ToList();
            ViewBag.rsml = rsml;
            ViewBag.ilan = ilan;
            return View();
        }
        [HttpPost]
        public ActionResult Images(int id,HttpPostedFileBase file)
        {
            string path = Path.Combine("/Content/images/" + file.FileName);
            file.SaveAs(Server.MapPath(path));
            Resim rsm = new Resim();
            rsm.ResimAd = file.FileName.ToString();
            rsm.IlanId = id;
            db.Resims.Add(rsm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Ilan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilans.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // GET: Ilan/Create
        public ActionResult Create()
        {
            ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirId", "SehirAd");
            ViewBag.durumlist = new SelectList(DurumGetir(), "DurumId", "DurumAd");
            return View();
        }

        // POST: Ilan/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IlanId,Açıklama,Fiyat,OdaSayisi,BanyoSayisi,Kredi,Alan,Kat,Telefon,Adres,UserName,SehirId,SemtId,DurumId,MahalleId,TipId")] Ilan ilan)
        {
            if (ModelState.IsValid)
            {
                ilan.UserName = User.Identity.Name;
                db.Ilans.Add(ilan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirId", "SehirAd");
            ViewBag.durumlist = new SelectList(DurumGetir(), "DurumId", "DurumAd");
            return View(ilan);
        }

        // GET: Ilan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilans.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirId", "SehirAd");
            ViewBag.durumlist = new SelectList(DurumGetir(), "DurumId", "DurumAd");
            ViewBag.SemtId = new SelectList(db.Semts, "SemtId", "SemtAd", ilan.SemtId);
            ViewBag.MahalleId = new SelectList(db.Mahalles, "MahalleId", "MahalleAd", ilan.MahalleId);
            ViewBag.TipId = new SelectList(db.Tips, "TipId", "TipAd", ilan.TipId);
            return View(ilan);
        }

        // POST: Ilan/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IlanId,Açıklama,Fiyat,OdaSayisi,BanyoSayisi,Kredi,Alan,Kat,Telefon,Adres,UserName,SehirId,SemtId,DurumId,MahalleId,TipId")] Ilan ilan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ilan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirId", "SehirAd");
            ViewBag.durumlist = new SelectList(DurumGetir(), "DurumId", "DurumAd");
            return View(ilan);
        }

        // GET: Ilan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilans.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // POST: Ilan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ilan ilan = db.Ilans.Find(id);
            db.Ilans.Remove(ilan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Ilan/Create.cshtml
@model Emlak.Models.Ilan

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, "Kullanıcı Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
               <button class="btn btn-success">@User.Identity.Name</button>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Açıklama,"Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Açıklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Açıklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyat,"Fiyat", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OdaSayisi,"Oda Sayısı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.OdaSayisi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OdaSayisi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BanyoSayisi,"Banyo Sayısı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.BanyoSayisi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BanyoSayisi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kredi,"Kredi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Kredi)
                    @Html.ValidationMessageFor(model => model.Kredi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alan,"Alan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Alan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kat,"Bulunduğu Kat", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Kat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon,"Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adres,"Adres", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.SehirId, "Şehir",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
               @if(ViewBag.sehirlist!=null)
               {
                   @Html.DropDownListFor(m=>m.SehirId, ViewBag.sehirlist as SelectList, "Sehir Seç", new { @class = "form-control" })
               }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemtId,"Semt", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
               @Html.DropDownListFor(m=>m.SemtId, new SelectList(""),"Semt Seç", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MahalleId, "Mahalle", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(m => m.MahalleId, new SelectList(""), "Mahalle Seç", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DurumId,"Durum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
               @if(ViewBag.durumlist!=null)
               {
                   @Html.DropDownListFor(m=>m.DurumId, ViewBag.durumlist as SelectList, "Durum Seç", new { @class = "form-control" })
               }
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TipId, "Tip", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
              @Html.DropDownListFor(m=>m.TipId, new SelectList(""),"Tip Seç", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-primary" />
                @Html.ActionLink("Ilan Listesi", "Index", null, new { @class = "btn btn-warning" })
            </div>
        </div>
    </div>
}

<script src="~/scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function() {
        $("#SehirId").change(function() {
            var sehirid = $(this).val();
            debugger
            $.ajax({
                type: "Post",
                url: "/Ilan/SemtGetir?SehirId=" + sehirid,
                contentType: "html",
                success: function(response) {
                    debugger
                    $("#SemtId").empty();
                    $("#SemtId").append(response);
                }
            })
        })
    })
</script>
<script>
    $(document).ready(function() {
        $("#SemtId").change(function() {
            var semtid = $(this).val();
            debugger
            $.ajax({
                type: "Post",
                url: "/Ilan/MahalleGetir?SemtId=" + semtid,
                contentType: "html",
                success: function(response) {
                    debugger
                    $("#MahalleId").empty();
                    $("#MahalleId").append(response);
                }
            })
        })
    })
</script>
<script>
    $(document).ready(function() {
        $("#DurumId").change(function() {
            var durumid = $(this).val();
            debugger
            $.ajax({
                type: "Post",
                url: "/Ilan/TipGetir?DurumId=" + durumid,
                contentType: "html",
                success: function(response) {
                    debugger
                    $("#TipId").empty();
                    $("#TipId").append(response);
                }
            })
        })
    })
</script>

Views/Ilan/Delete.cshtml
@model Emlak.Models.Ilan

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <h3>Bu ilanı silmek istediğiniz emin misiniz?</h3>
    <div>

        <dl class="dl-horizontal">
            <dt>
               Mahalle
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MahalleId)
            </dd>

            <dt>
               Tip
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TipId)
            </dd>

            <dt>
               Açıklama
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Açıklama)
            </dd>

            <dt>
               Fiyat
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fiyat)
            </dd>

            <dt>
               Oda Sayısı
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OdaSayisi)
            </dd>

            <dt>
                Banyo Sayısı
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BanyoSayisi)
            </dd>

            <dt>
               Kredi
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kredi)
            </dd>

            <dt>
               Alan
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Alan)
            </dd>

            <dt>
               Kat
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kat)
            </dd>

            <dt>
                Telefon
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Telefon)
            </dd>

            <dt>
                Adres
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Adres)
            </dd>

            <dt>
               Kullanıcı Adı
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
               Şehir
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SehirId)
            </dd>

            <dt>
                Semt
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SemtId)
            </dd>

            <dt>
               Durum
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DurumId)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-danger" /> |
                @Html.ActionLink("Ilan Listesi", "Index", null, new { @class = "btn btn-warning" })
            </div>
        }
    </div>
</div>

Views/Ilan/Details.cshtml
@model Emlak.Models.Ilan

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ilan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mahalle.MahalleAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mahalle.MahalleAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tip.TipAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tip.TipAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Açıklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Açıklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OdaSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OdaSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BanyoSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BanyoSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kredi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kredi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SehirId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SehirId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SemtId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SemtId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DurumId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DurumId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IlanId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Ilan/Images.cshtml
@{
    ViewBag.Title = "Images";
}

<div class="container">
    @{ 
        Html.BeginForm("Images", "Ilan", FormMethod.Post, new { enctype = "multipart/Form-data" });
        foreach (var item in  ViewBag.ilan)
        {
            <h3>@item.IlanId Numaralı ilan için Resim Ekle</h3>
            <table>
                <tr>
                    <td>Resim Seç</td>
                    <td><input type="hidden" name="id" value="@item.IlanId"/></td>
                    <td><input type="file" name="file" /> </td>
                    <td><input type="submit" value="Ekle" class="btn btn-primary"/></td>
                    <td>- @Html.ActionLink("Ilan Listesi", "Index", null, new { @class = "btn btn-warning" })</td>
                </tr>
            </table>
        }
    }
    <br />
    <div class="row">
        @foreach (var item in ViewBag.rsml)
        {
            <div class="col-md-4">
                <div class="thumbnail">
                    <img  src="~/Content/images/@item.ResimAd" height="250" width="250"/>
                </div>
            </div>
        }
    </div>
</div>

Views/Ilan/Index.cshtml
@model IEnumerable<Emlak.Models.Ilan>

@{
    ViewBag.Title = "Index";
}

<div class="container">

    <div class="row">
        @Html.Action("PartialFiltre", "Home")

        <!--ilan Listesi-->
        <br />
        <div class="col-md-9">
            <div class="thumbnail" style="width:845px;">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/Home/Index">Anasayfa</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Ilan Listesi</li>
                    </ol>
                </nav>

                <br />
                <table class="table">
                    <tr>
                        <th>
                           Mahalle
                        </th>
                        <th>
                            Tip
                        </th>
                       
                     
                        <th>
                           Adres
                        </th>
                      
                        <th>
                            Şehir
                        </th>
                        <th>
                           Semt
                        </th>
                        <th>
                            Durum
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.MahalleAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tip.TipAd)
                            </td>
                           
                            <td>
                                @Html.DisplayFor(modelItem => item.Adres)
                            </td>
                         
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.Semt.Sehir.SehirAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.Semt.SemtAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tip.Durum.DurumAd)
                            </td>
                            <td>
                                <a class="btn btn-success" href="@Url.Action("Images", new { id = item.IlanId })"><i class="fa fa-camera" aria-hidden="true"></i> Resim Ekle</a>
                                <a class="btn btn-primary" href="@Url.Action("Edit", new { id = item.IlanId })"><i class="fa fa-edit" aria-hidden="true"></i> Düzenle</a>
                                <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.IlanId })"><i class="fa fa-trash" aria-hidden="true"></i> Sil</a>
                            </td>
                        </tr>
                    }

                </table>
               
            </div>
        </div>
    </div>
</div>